### ISSUE TITLE
how do i upgrade the icinga container

### ISSUE THREAD

**Issue by chesty** [whatwedo/docker-base-images#2]
Hi,

with /bin/firstboot

```
if [ -f /etc/firstboot/flag ];
then
   exit
fi

date > /etc/firstboot/flag
echo "Run content of /bin/firstboot..."
...
```

would you be open to making the firstboot check something like

```
if [[ ! -z `mysql -h $DB_SERVER -u $DB_USER -p$DB_PW -P $DB_PORT -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='$DB_NAME'"  $DB_NAME` ]]; then 
  exit ; 
fi
echo "Run content of /bin/firstboot..."
...
``` 

I'm new to docker, I can't see how to upgrade the container when you're checking the existence of a file to determine first boot. and as I typed that, I thought I could probably make /etc/firstboot/flag a volume.

I guess my real question is, how do i upgrade the container when a new image drops? what's the docker way?

**Comment by chesty** [comment]
well this is interesting, there's already an /etc/firstboot volume (i can't see it in the dockerfile), but when I stop my container, all the volumes get deleted. I didn't think that was supposed to happen. ie

this is before I start icinga
```
ls -l /var/lib/docker/volumes/
total 124
drwxr-xr-x 3 root root   4096 Aug 23 14:18 0f29c78cf884631423dc04ed0e7794461daf75cff4cd3d2187a129449500c42a
drwxr-xr-x 3 root root   4096 Aug 23 14:18 2fe121a73abf8b78985433ce68267838e70350267d298647b317b4d0f5d2ad2d
drwxr-xr-x 3 root root   4096 Aug 23 14:18 4d0edee9b9795458433f0a254c678f31d58a950df0da414c7ed52b12cbd5ac68
drwxr-xr-x 3 root root   4096 Aug 23 14:18 9a705a80e1ceae120eacbfcc7cb2713c24beba412b79ce462b4ab4ddc0d2e82b
drwxr-xr-x 3 root root   4096 Aug 23 14:18 a8757b909f93296660e3579a78552e523deec405765db80de9eb1cb00becae29
drwxr-xr-x 3 root root   4096 Aug 23 14:18 e01d85556a51da1f123958fc8ac8c63d91913a801a10200fbd6dd228de23f53a
-rw------- 1 root root 131072 Aug 27 15:17 metadata.db
```
I start icinga with the following, with --rm but I thought the volumes were suppose to persist.
```
/usr/bin/docker run --rm --net=kk --net-alias=icinga2v1 --name icinga2v1 -p 8085:80 -e CONTAINER_TIMEZONE='Australia/Sydney' -e DB_USER=icinga2v1 -e DB_PW=secret -e DB_SERVER=mariadbv1 -e DB_PORT=3306 -e DB_NAME=icinga2v1 -e ICINGAADMIN_PW=secret  -ti  whatwedo/icinga2
```

then ls -l /var/lib/docker/volumes/ again
```
ls -l /var/lib/docker/volumes/
total 144
drwxr-xr-x 3 root root   4096 Aug 23 14:18 0f29c78cf884631423dc04ed0e7794461daf75cff4cd3d2187a129449500c42a
drwxr-xr-x 3 root root   4096 Aug 27 15:33 19d9b07f25639121457266ca0bd6a7780786164ffa6b6969e2d3ec588c2c8b39
drwxr-xr-x 3 root root   4096 Aug 27 15:33 20c23355769cfc3ac4999d5e20998d4a867f9facd4cec56869bada611522961e
drwxr-xr-x 3 root root   4096 Aug 23 14:18 2fe121a73abf8b78985433ce68267838e70350267d298647b317b4d0f5d2ad2d
drwxr-xr-x 3 root root   4096 Aug 27 15:33 3fdfc142ad385a71548f01c3e848dd78c426765393cda75ff603b85f02103465
drwxr-xr-x 3 root root   4096 Aug 23 14:18 4d0edee9b9795458433f0a254c678f31d58a950df0da414c7ed52b12cbd5ac68
drwxr-xr-x 3 root root   4096 Aug 27 15:33 7d7d0fe230895916592dc22bc0550c1cff87ea8f25bbaa776fb86dbef49fa325
drwxr-xr-x 3 root root   4096 Aug 23 14:18 9a705a80e1ceae120eacbfcc7cb2713c24beba412b79ce462b4ab4ddc0d2e82b
drwxr-xr-x 3 root root   4096 Aug 23 14:18 a8757b909f93296660e3579a78552e523deec405765db80de9eb1cb00becae29
drwxr-xr-x 3 root root   4096 Aug 27 15:33 d86b4df04216de3bcb1f3f1c2f8f97486b7044c50523af64ff4e1f00d807e44f
drwxr-xr-x 3 root root   4096 Aug 23 14:18 e01d85556a51da1f123958fc8ac8c63d91913a801a10200fbd6dd228de23f53a
-rw------- 1 root root 131072 Aug 27 15:33 metadata.db
```
then I stop the container, and ls the volume dir again
```
ls -l /var/lib/docker/volumes/
total 124
drwxr-xr-x 3 root root   4096 Aug 23 14:18 0f29c78cf884631423dc04ed0e7794461daf75cff4cd3d2187a129449500c42a
drwxr-xr-x 3 root root   4096 Aug 23 14:18 2fe121a73abf8b78985433ce68267838e70350267d298647b317b4d0f5d2ad2d
drwxr-xr-x 3 root root   4096 Aug 23 14:18 4d0edee9b9795458433f0a254c678f31d58a950df0da414c7ed52b12cbd5ac68
drwxr-xr-x 3 root root   4096 Aug 23 14:18 9a705a80e1ceae120eacbfcc7cb2713c24beba412b79ce462b4ab4ddc0d2e82b
drwxr-xr-x 3 root root   4096 Aug 23 14:18 a8757b909f93296660e3579a78552e523deec405765db80de9eb1cb00becae29
drwxr-xr-x 3 root root   4096 Aug 23 14:18 e01d85556a51da1f123958fc8ac8c63d91913a801a10200fbd6dd228de23f53a
-rw------- 1 root root 131072 Aug 27 15:33 metadata.db
```

is that supposed to happen? 
https://docs.docker.com/engine/tutorials/dockervolumes/ says
Data volumes persist even if the container itself is deleted.

**Comment by chesty** [comment]
alright, reading further, --rm deletes anonymous volumes. so that explains that.
I still don't know how /etc/firstboot is a volume yet I can't see it defined in the dockerfile.

**Comment by n3r0-ch** [comment]
The `/etc/firstboot` volume is in the `whatwedo/base` image defined (https://github.com/whatwedo/docker-base-images/blob/master/dist/base/Dockerfile#L33) on which the `whatwedo/icinga` depends.

We had a lot of troubles with anonymous volumes in the past. So we decided to mount host directories as volumes if possible. We have a lot less problems this way. 

Below you find a `docker-compose.yml` file to run the Icinga container:

```
db:
    image: whatwedo/mariadb:latest
    volumes:
        - [YOUR_DATA_DIR]/db/var/lib/mysql:/var/lib/mysql
        - [YOUR_DATA_DIR]/db/etc/firstboot:/etc/firstboot
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=secretPassword

icinga:
    image: whatwedo/icinga2:latest
    restart: always
    environment:
        - DB_USER=root
        - DB_PW=secretPassword
        - DB_SERVER=db
        - DB_PORT=3306
        - ICINGAADMIN_PW=secretPassword
    volumes:
        - [YOUR_DATA_DIR]/icinga/etc/icingaweb2:/etc/icingaweb2
        - [YOUR_DATA_DIR]/icinga/etc/icinga2/conf.d:/etc/icinga2/conf.d
        - [YOUR_DATA_DIR]/icinga/etc/firstboot:/etc/firstboot
    ports:
        - "80:80"
    links:
        - "db:db"

```

Let us know if you have further questions.

**Comment by chesty** [comment]
thanks n3r0

I can't test atm, when setting up a brand new container with brand new host directories which are empty, does docker copy (eg) /etc/icingaweb2 from inside the container to [YOUR_DATA_DIR]/icinga/etc/icingaweb2 ?

I think this says not
"Volumes are initialized when a container is created. If the container’s base image contains data at the specified mount point, that existing data is copied into the new volume upon volume initialization. (Note that this does not apply when mounting a host directory.)"

what if during the build, dockerfile copies /etc/icingaweb2 to /etc/copy/icingaweb2 and /bin/firstboot tests if /etc/icingaweb2/ is empty, and if it is, copies /etc/copy/icingaweb2 /etc/icingaweb2

just thinking out aloud.

**Comment by n3r0-ch** [comment]
You are totally right. The initialization of /etc/icingaweb2 won't work if it is a mounted host directory. I opened a new issue #3 for this. I'm currently a little bit busy. You are welcome to submit a pull request. 

As a temporary workaround you can start the container with `/etc/icingaweb2` as anonymous volume, copy the content of the volume, and recreate the container with `/etc/icingaweb2` as a mounted host directory. Or you can use the following configuration without `/etc/icingaweb2` as a mounted host directory. Perhaps this is working stable for you.

```
db:
    image: whatwedo/mariadb:latest
    volumes:
        - [YOUR_DATA_DIR]/db/var/lib/mysql:/var/lib/mysql
        - [YOUR_DATA_DIR]/db/etc/firstboot:/etc/firstboot
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=secretPassword

icinga:
    image: whatwedo/icinga2:latest
    restart: always
    environment:
        - DB_USER=root
        - DB_PW=secretPassword
        - DB_SERVER=db
        - DB_PORT=3306
        - ICINGAADMIN_PW=secretPassword
    volumes:
        - [YOUR_DATA_DIR]/icinga/etc/icinga2/conf.d:/etc/icinga2/conf.d
        - [YOUR_DATA_DIR]/icinga/etc/firstboot:/etc/firstboot
    ports:
        - "80:80"
    links:
        - "db:db"
```

All other volumes should be working as mounted host directory without any troubles.
