### ISSUE TITLE
How to add PHP extension like Mongodb ? 

### ISSUE THREAD

**Issue by SirMishaa** [whatwedo/docker-base-images#41]
Hello,

I would like to add ``mongodb`` extension.
I can't put it in my composer.json because If I do, I've got an error message  
``Class "MongoDB\Driver\Monitoring\CommandSubscriber" not found while loading "Doctrine\Bundle\MongoDBBundle\APM\PSRCommandLogger".``

So is there any way to do it easily ?

**Comment by s4mpl3d** [comment]
@SirMishaa you can just install the extension inside your docker-container:

f.ex inside your Dockerfile
```
FROM whatwedo/nginx-php:v2.2 as base
RUN apk add php-mongodb@php

```

**Comment by SirMishaa** [comment]
Ah, so simple.

Thank you very much for the quick response

**Comment by SirMishaa** [comment]
I guess, I've to use ``build`` in my docker-compose file ? Like this :
```yaml
version: '3.8'

services:
    php:
        build:
            dockerfile: docker/php/Dockerfile
            context: .
        ports:
        -   4000:80
        volumes:
        -   .:/var/www:cached
```
